#!/usr/bin/env python3
"""
Generate idempotent SQL to seed the IOA reporting categories and codes.

Source of truth is `web/src/constants/ioaConstants.ts` so the frontend's
display labels and the database seed stay in lockstep — change the .ts file,
re-run this script, re-apply the SQL.

Usage:
    # Emit SQL to stdout (default):
    python service/scripts/seed_ioa.py > service/seed_ioa.sql

    # Or pipe straight into the running dev DB:
    python service/scripts/seed_ioa.py | docker compose exec -T db \\
        psql -U "$DB_USER" -d "$DB_NAME"

UUIDs for categories and codes are derived deterministically via uuid5, so
rebuilding the dev DB yields the same ids every time. The IOA *organization*
UUID is hard-coded (it's referenced from the frontend at
`web/src/tools/useIoaOrgId.ts` and seeded in `service/schema.sql`); that one
ID is intentionally NOT regenerated here.

The emitted SQL uses `ON CONFLICT (id) DO NOTHING`, so re-running is safe.
Renaming an IOA category or code description will *not* update existing rows
— for that, change the script to emit `ON CONFLICT (id) DO UPDATE`. We don't
do that yet because IOA codes are reference data and shouldn't drift.
"""

from __future__ import annotations

import os
import re
import sys
import uuid

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
TS_FILE = os.path.join(REPO_ROOT, 'web', 'src', 'constants', 'ioaConstants.ts')

# Stable namespace so uuid5(NAMESPACE, "<key>") is identical forever.
NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, 'ombuddi.com/ioa-seed')

# Must match service/schema.sql and web/src/tools/useIoaOrgId.ts.
IOA_ORG_ID = '628b5737-43e6-49c7-a632-2f723a455e59'


def sql_quote(s: str) -> str:
    """Single-quote and escape for inclusion in a SQL VALUES list."""
    return "'" + s.replace("'", "''") + "'"


def parse_ts_file(path: str) -> tuple[list[str], list[tuple[str, str]]]:
    """Pull `ioaCategories` (list of names) and `ioaCodes` (list of [code, desc])
    out of the TS source file. Resilient to whitespace and line wrapping."""
    with open(path, 'r') as f:
        content = f.read()

    codes_match = re.search(
        r'export\s+const\s+ioaCodes\s*=\s*\[(.*?)\]\s*\n',
        content,
        re.DOTALL,
    )
    if not codes_match:
        raise RuntimeError(f'Could not find ioaCodes in {path}')
    code_pairs = re.findall(
        r"\[\s*'([^']+)'\s*,\s*'([^']*)'\s*\]",
        codes_match.group(1),
    )
    if not code_pairs:
        raise RuntimeError(f'ioaCodes parsed empty from {path}')

    cats_match = re.search(
        r'export\s+const\s+ioaCategories\s*=\s*\[(.*?)\]\s*\n',
        content,
        re.DOTALL,
    )
    if not cats_match:
        raise RuntimeError(f'Could not find ioaCategories in {path}')
    categories = re.findall(r"'([^']*)'", cats_match.group(1))
    if len(categories) != 9:
        raise RuntimeError(
            f'Expected 9 IOA categories, found {len(categories)} in {path}'
        )

    return categories, code_pairs


def category_id(name: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f'category:{name}'))


def code_id(code: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f'code:{code}'))


def emit(categories: list[str], code_pairs: list[tuple[str, str]]) -> str:
    out: list[str] = []
    out.append('-- Generated by service/scripts/seed_ioa.py. Do not edit by hand.')
    out.append('-- Source: web/src/constants/ioaConstants.ts')
    out.append('--')
    out.append('-- Re-run after changing ioaConstants.ts:')
    out.append('--   python service/scripts/seed_ioa.py > service/seed_ioa.sql')
    out.append('')
    out.append('BEGIN;')
    out.append('')
    out.append('-- IOA code categories')
    for idx, name in enumerate(categories):
        cid = category_id(name)
        out.append(
            f"INSERT INTO code_categories (id, organization_id, name, index, soft_delete) "
            f"VALUES ({sql_quote(cid)}, {sql_quote(IOA_ORG_ID)}, "
            f"{sql_quote(name)}, {idx}, FALSE) "
            f"ON CONFLICT (id) DO NOTHING;"
        )
    out.append('')
    out.append('-- IOA codes')
    for code, description in code_pairs:
        if not code or not code[0].isdigit():
            raise RuntimeError(
                f'Code {code!r} does not start with a digit; '
                f'cannot map to a category index'
            )
        # First char (1-9) maps to category list index (0-8).
        cat_idx = int(code[0]) - 1
        if not (0 <= cat_idx < len(categories)):
            raise RuntimeError(
                f'Code {code!r} maps to out-of-range category index {cat_idx}'
            )
        cat_id = category_id(categories[cat_idx])
        out.append(
            f"INSERT INTO codes (id, organization_id, category_id, code, description, soft_delete) "
            f"VALUES ({sql_quote(code_id(code))}, {sql_quote(IOA_ORG_ID)}, "
            f"{sql_quote(cat_id)}, {sql_quote(code)}, {sql_quote(description)}, FALSE) "
            f"ON CONFLICT (id) DO NOTHING;"
        )
    out.append('')
    out.append('COMMIT;')
    return '\n'.join(out) + '\n'


def main() -> int:
    categories, code_pairs = parse_ts_file(TS_FILE)
    sys.stdout.write(emit(categories, code_pairs))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
